// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using System.Linq;
using System.Security.Cryptography;
using System.Text;
using CookApps.SpecData.Generator;

[GeneratorSpecDataResource]
public static partial class SpecDataResourceLoader
{
    private static readonly byte[] _key = {97, 52, 40, 117, 71, 99, 64, 97, 90, 48, 92, 111, 47, 95, 105, 59};
}
