// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>


/// 플레이어 상태
public enum PlayerState
{
    Idle = 1,
    Move = 2,
    Attack = 3,
    Skill = 4,
    Dead = 5,
}

/// 몬스터 상태
public enum MonsterState
{
    Move = 1,
    Chase = 2,
    Attack = 3,
    Dead = 4,
}

/// 유닛 상태
public enum UnitState
{
    Idle = 1,
    Chase = 2,
    Attack = 3,
    Return = 4,
    Dead = 5,
}

/// 건물 종류
public enum BuildingState
{
    Wait = 1,
    Idle = 2,
    Crash = 3,
}

/// 몬스터 종류
public enum MonsterType
{
    Monster_1_1_1_Mouse = 1,
    Monster_1_1_2_Pot = 2,
    Monster_1_1_3_Bunny = 3,
    Monster_1_1_Boss_Treeman = 4,
}

/// 건물 종류
public enum BuildingType
{
    Castle = 1,
    House = 2,
    Tower = 3,
    Barracks = 4,
    Wall = 5,
}

/// 유닛 종류
public enum UnitType
{
    Knight = 1,
    Archer = 2,
}

/// 사운드
public enum Sound
{
    BGM = 0,
    Effect = 1,
}
