// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using CookApps.SpecData.Generator;


[GeneratorSpecData]
public partial class CharacterStatus
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public float HP;
    public float MoveSpeed;
    public float RegenerationTime;
    public bool IsAttackSplash;
    public float AttackDamage;
    public float AttackWaitTime;
    public float AttackRange;
    public int AttackTargetCount;
    public bool IsSkillSplash;
    public float SkillDamage;
    public float SkillWaitTime;
    public float SkillRange;
    public int SkillTargetCount;
    public float SkillActiveTime;
    public float SkillCooltime;
    public float SkillSpeed;
}

[GeneratorSpecData]
public partial class MonsterStatus
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public global::MonsterType MonsterType;
    public float HP;
    public float MoveSpeed;
    public float Damage;
    public float WaitTime;
    public float Range;
}

[GeneratorSpecData]
public partial class UnitStatus
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public global::UnitType UnitType;
    public float HP;
    public float MoveSpeed;
    public float Damage;
    public float WaitTime;
    public float Range;
}

[GeneratorSpecData]
public partial class BuildingStatus
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public global::BuildingType BuildingType;
    public int Level;
    public float HP;
    public int UpgradeID;
}

[GeneratorSpecData]
public partial class UpgradeStatus
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public int Level;
    public int Cost;
}

[GeneratorSpecData]
public partial class TowerStatus
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public int Level;
    public float Damage;
    public float WaitTime;
    public float Range;
    public int TargetCount;
    public bool IsSplash;
}

[GeneratorSpecData]
public partial class StageStatus
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public int[] Waves = global::System.Array.Empty<int>();
}

[GeneratorSpecData]
public partial class WaveStatus
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public int[] Troops = global::System.Array.Empty<int>();
}

[GeneratorSpecData]
public partial class TroopStatus
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public int[] Generators = global::System.Array.Empty<int>();
}

[GeneratorSpecData]
public partial class GeneratorStatus
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public global::MonsterType Type;
    public int Count;
    public float X;
    public float Y;
}
